export const allCategories = [
  "culture-festival",
  "music",
  "film",
  "food",
  "travel",
  "conference",
  "meetup",
  "trade-show",
  "seminar",
  "corporate",
  "workshop",
  "company-party",
  "product-launch",
  "promotional",
]
